Repository gurtejboparai/bookwyrm, pull requests merged in 2022-03, with the labels that each got.

#56 User/antony/#42
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/controller/ReviewController.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/input/ReviewUploadInput.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/payload/ReviewUploadPayload.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/validator/ReviewUploadValidator.java
Labels: Spring

#77 User/antony/#74
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/comment/controller/CommentController.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/comment/input/CommentUploadInput.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/comment/payload/CommentUploadPayload.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/comment/validator/CommentUploadValidator.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/controller/ReviewController.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/input/ReviewUploadInput.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/payload/ReviewUploadPayload.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/validator/ReviewUploadValidator.java
Labels: Spring

#76 Created ReviewService.js
  bookwyrm_frontend/src/services/ReviewService.js
Labels: dev task, Reviews

#92 User/antony/#67
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/payload/BookSearchPayload.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/payload/BookUploadPayload.java
  bookwyrm_backend/src/test/java/com/bookwyrm/backend/integration/book/controller/BookControllerTests.java
Labels: Spring

#102 User/antony/#65
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/payload/BookDetailSearchPayload.java
  bookwyrm_backend/src/test/java/com/bookwyrm/backend/integration/book/controller/BookControllerTests.java
Labels: Spring

#148 User/cameron jung/#123
  bookwyrm_frontend/package-lock.json
  bookwyrm_frontend/package.json
  bookwyrm_frontend/src/App.vue
  bookwyrm_frontend/src/components/CommentComponent.vue
  bookwyrm_frontend/src/components/RatingComponent.vue
  bookwyrm_frontend/src/components/ReviewComponent.vue
  bookwyrm_frontend/src/components/StarRatingWrapperComponent.vue
  bookwyrm_frontend/src/views/BookDetail.vue
Labels: Vue, Ratings

#164 Fixed the focus mode's author display so it doesn't always display the author as "- guest -"
  bookwyrm_frontend/src/components/ReviewComponent.vue
Labels: bug

#171 User/cameron jung/#169
  bookwyrm_frontend/src/components/CommentComponent.vue
  bookwyrm_frontend/src/components/RatingComponent.vue
  bookwyrm_frontend/src/components/ReviewComponent.vue
  bookwyrm_frontend/src/components/StarRatingWrapperComponent.vue
  bookwyrm_frontend/tests/unit/components/CommentComponent.spec.js
  bookwyrm_frontend/tests/unit/components/RatingComponent.spec.js
  bookwyrm_frontend/tests/unit/components/StarRatingWrapperComponent.spec.js
Labels: Testing
