Repository gurtejboparai/bookwyrm, pull requests merged in 2022-04, with the labels that each got.

#192 #174 Update testing plan
  .github/BookWyrm_Test_Plan.pdf
  .github/workflows/BookWyrm_Test_Plan.pdf
Labels: documentation, Testing

#234 User/antony/#212
  bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java
  bookwyrm_frontend/package-lock.json
  bookwyrm_frontend/package.json
  bookwyrm_frontend/src/components/CarouselComponent.vue
  bookwyrm_frontend/src/services/BookService.js
  bookwyrm_frontend/src/views/Home.vue
Labels: Vue, Home Page

#249 Updating test plan
  bookwyrm_tests/BookWyrm_Test_Plan.pdf
Labels: documentation
